// Code generated by mockery. DO NOT EDIT.

package accrual

import (
	context "context"

	model "github.com/mgfan1/go-musthave-diploma/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// mockOrders is an autogenerated mock type for the Orders type
type mockOrders struct {
	mock.Mock
}

// ApplyAccrual provides a mock function with given fields: ctx, number, result
func (_m *mockOrders) ApplyAccrual(ctx context.Context, number string, result model.AccrualResult) error {
	ret := _m.Called(ctx, number, result)

	if len(ret) == 0 {
		panic("no return value specified for ApplyAccrual")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.AccrualResult) error); ok {
		r0 = rf(ctx, number, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClaimPending provides a mock function with given fields: ctx, limit
func (_m *mockOrders) ClaimPending(ctx context.Context, limit int) ([]string, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ClaimPending")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]string, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []string); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockOrders creates a new instance of mockOrders. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockOrders(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockOrders {
	mock := &mockOrders{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
