// Code generated by mockery. DO NOT EDIT.

package handler

import (
	context "context"

	model "github.com/mgfan1/go-musthave-diploma/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// mockOrderService is an autogenerated mock type for the OrderService type
type mockOrderService struct {
	mock.Mock
}

// List provides a mock function with given fields: ctx, userID
func (_m *mockOrderService) List(ctx context.Context, userID int64) ([]model.Order, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]model.Order, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []model.Order); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upload provides a mock function with given fields: ctx, userID, number
func (_m *mockOrderService) Upload(ctx context.Context, userID int64, number string) (bool, error) {
	ret := _m.Called(ctx, userID, number)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (bool, error)); ok {
		return rf(ctx, userID, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) bool); ok {
		r0 = rf(ctx, userID, number)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, userID, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockOrderService creates a new instance of mockOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockOrderService {
	mock := &mockOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
