// Code generated by mockery. DO NOT EDIT.

package service

import (
	context "context"
	iter "iter"

	mock "github.com/stretchr/testify/mock"

	model "github.com/mgfan1/go-musthave-diploma/internal/model"
)

// mockOrderRepository is an autogenerated mock type for the OrderRepository type
type mockOrderRepository struct {
	mock.Mock
}

// ClaimPendingOrders provides a mock function with given fields: ctx, limit
func (_m *mockOrderRepository) ClaimPendingOrders(ctx context.Context, limit int) ([]string, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ClaimPendingOrders")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]string, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []string); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateOrder provides a mock function with given fields: ctx, userID, number
func (_m *mockOrderRepository) CreateOrder(ctx context.Context, userID int64, number string) (int64, bool, error) {
	ret := _m.Called(ctx, userID, number)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 int64
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (int64, bool, error)); ok {
		return rf(ctx, userID, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) int64); ok {
		r0 = rf(ctx, userID, number)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) bool); ok {
		r1 = rf(ctx, userID, number)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, string) error); ok {
		r2 = rf(ctx, userID, number)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateOrder provides a mock function with given fields: ctx, number, status, accrual
func (_m *mockOrderRepository) UpdateOrder(ctx context.Context, number string, status model.OrderStatus, accrual *model.Money) error {
	ret := _m.Called(ctx, number, status, accrual)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.OrderStatus, *model.Money) error); ok {
		r0 = rf(ctx, number, status, accrual)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserOrders provides a mock function with given fields: ctx, userID
func (_m *mockOrderRepository) UserOrders(ctx context.Context, userID int64) iter.Seq2[model.Order, error] {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UserOrders")
	}

	var r0 iter.Seq2[model.Order, error]
	if rf, ok := ret.Get(0).(func(context.Context, int64) iter.Seq2[model.Order, error]); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[model.Order, error])
		}
	}

	return r0
}

// newMockOrderRepository creates a new instance of mockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockOrderRepository {
	mock := &mockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
