// Code generated by mockery. DO NOT EDIT.

package service

import (
	context "context"
	iter "iter"

	mock "github.com/stretchr/testify/mock"

	model "github.com/mgfan1/go-musthave-diploma/internal/model"
)

// mockBalanceRepository is an autogenerated mock type for the BalanceRepository type
type mockBalanceRepository struct {
	mock.Mock
}

// Balance provides a mock function with given fields: ctx, userID
func (_m *mockBalanceRepository) Balance(ctx context.Context, userID int64) (model.Balance, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Balance")
	}

	var r0 model.Balance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (model.Balance, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) model.Balance); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(model.Balance)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserWithdrawals provides a mock function with given fields: ctx, userID
func (_m *mockBalanceRepository) UserWithdrawals(ctx context.Context, userID int64) iter.Seq2[model.Withdrawal, error] {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UserWithdrawals")
	}

	var r0 iter.Seq2[model.Withdrawal, error]
	if rf, ok := ret.Get(0).(func(context.Context, int64) iter.Seq2[model.Withdrawal, error]); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[model.Withdrawal, error])
		}
	}

	return r0
}

// Withdraw provides a mock function with given fields: ctx, userID, order, sum
func (_m *mockBalanceRepository) Withdraw(ctx context.Context, userID int64, order string, sum model.Money) error {
	ret := _m.Called(ctx, userID, order, sum)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, model.Money) error); ok {
		r0 = rf(ctx, userID, order, sum)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockBalanceRepository creates a new instance of mockBalanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockBalanceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockBalanceRepository {
	mock := &mockBalanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
