// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/mgfan1/go-musthave-diploma/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Fetcher is an autogenerated mock type for the Fetcher type
type Fetcher struct {
	mock.Mock
}

// Order provides a mock function with given fields: ctx, number
func (_m *Fetcher) Order(ctx context.Context, number string) (model.AccrualResult, error) {
	ret := _m.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for Order")
	}

	var r0 model.AccrualResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.AccrualResult, error)); ok {
		return rf(ctx, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.AccrualResult); ok {
		r0 = rf(ctx, number)
	} else {
		r0 = ret.Get(0).(model.AccrualResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFetcher creates a new instance of Fetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Fetcher {
	mock := &Fetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
